### ISSUE TITLE
Can’t reach tscans from safari, chrome, etc

### ISSUE THREAD

**Issue by doronsacha** [michael-maltsev/technion-scans#7]
Hi,
Thanks you for your great work on cheesfork, tscans and more.
When trying to reach tscans I have this error.
Not sure if this is the good way to report this so sorry:

This site can’t be reached

tscans.cf’s server IP address could not be found.
Try:
Checking the connection
ERR_NAME_NOT_RESOLVED

**Comment by michael-maltsev** [comment]
It's a global issue with .cf domains. I also wrote about it [here](https://www.facebook.com/cheesefork.technion/posts/pfbid0jZfuVyh5C969VTrDvHz1pK89BxApKXNTLtW8HcrrH4zkGbVuLAkSz7shZRSuV8jDl). For now, you can use the following backup address:
https://tscans.netlify.app/
